<?//Write a PHP script to script to display time table of your class( use HTML table tags in echo).?>

<?php
echo '
<center>        
<table border="1" style="text-align:center; border-collapse: collapse;">
    <tr>
        <th>Day/Time</th>
        <th>8:00-8:45</th>
        <th>8:45-9:30</th>
        <th>9:30-10:15</th>
        <th>10:15-11:00</th>
        <th>11:00-11:45</th>
        <th>11:45-12:30</th>
    </tr>
    <tr>
        <th>Monday</th>
        <td colspan="4">
            E1/1:CPP<br>
            E1/2:PPL<br>
            E1/3:CPP<br>
            E1/4:WT
        </td>
        <td>WT</td>
        <td>PPL</td>
    </tr>
    <tr>
        <th>Tuesday</th>
        <td>CPP</td>
        <td>PPL</td>
        <td>CPP</td>
        <td>EVS-II</td>
        <td>SE</td>
        <td>EVS-II</td>      
    </tr>
    <tr>
        <th>Wednesday</th>
        <td>CPP</td>
        <td>SE</td>
        <td>CPP</td>
        <td>WT</td>
        <td>SE</td>
        <td>WT</td>    
    </tr>
    <tr>
        <th>Thursday</th>
        <td colspan="4">
            E1/1:WT<br>
            E1/2:WT<br>
            E1/3:WT<br>
            E1/4:CPP
        </td>
        <td>LC-II</td>
        <td>SE</td>       
    </tr>
    <tr>
        <th>Friday</th>
        <td>WT</td>
        <td>WT</td>
        <td>TPO</td>
        <td>LC-II</td>
        <td>CPP</td>
        <td>SE</td>      
    </tr>
    <tr>
        <th>Saturday</th>
        <td colspan="4">
            E1/1:PPL<br>
            E1/2:CPP<br>
            E1/3:PPL<br>
            E1/4:PPL
        </td>
        <td>-</td>
        <td>-</td>
    </tr>
</table>
</center>
';
?>
